/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schemaTypes/extract.json
export type Instagram = {
  _type: 'instagram'
  marker?: boolean
}

export type Gallery = {
  _type: 'gallery'
  images: Array<{
    image: ImageWithAlt
    _key: string
  }>
}

export type Price = {
  _type: 'price'
  title: string
  disclaimer?: string
  prices: Array<{
    amount: string
    caption?: string
    _type: 'priceItem'
    _key: string
  }>
}

export type ContactForm = {
  _type: 'contactForm'
  image?: ImageWithAlt
  marker?: boolean
}

export type CourseForm = {
  _type: 'courseForm'
  marker?: boolean
}

export type TitleAndRichText = {
  _type: 'titleAndRichText'
  title: string
  body: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type TextContent = {
  _type: 'textContent'
  title: string
  content: string
}

export type IconsAndTitles = {
  _type: 'iconsAndTitles'
  title: string
  iconsandtitles: Array<
    {
      _key: string
    } & IconWithTitle
  >
}

export type CoursePlan = {
  _type: 'coursePlan'
  title: string
  content: string
  items: Array<{
    image: ImageWithAlt
    title: string
    textLines?: Array<{
      boldText?: string
      caption?: string
      _type: 'textLine'
      _key: string
    }>
    _type: 'coursePlanItem'
    _key: string
  }>
}

export type ImageBlock = {
  _type: 'imageBlock'
  image: ImageWithAlt
}

export type ThreeParagraphs = {
  _type: 'threeParagraphs'
  fistparagraph: string
  secondparagraph: string
  thirdparagraph: string
  firstimage: ImageWithAlt
  secondimage: ImageWithAlt
}

export type AboutUsContent = {
  _type: 'aboutUsContent'
  firstparagraph: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  secondparagraph: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  link?: string
  firstimage: ImageWithAlt
  secondimage: ImageWithAlt
  thirdimage: ImageWithAlt
}

export type SubHero = {
  _type: 'subHero'
  title: string
  subtitle?: string
  image: ImageWithAlt
}

export type Faq = {
  _type: 'faq'
  title?: string
  questions: Array<
    {
      _key: string
    } & FaqItem
  >
  backgroundimage?: ImageWithAlt
  link?: string
  noPadding?: boolean
  biggerMaxWidth?: boolean
  headingOnLeft?: boolean
}

export type CourseReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'course'
}

export type Courses = {
  _type: 'courses'
  title?: string
  content?: string
  link?: string
  kursy: Array<
    {
      _key: string
    } & CourseReference
  >
}

export type AboutCenter = {
  _type: 'aboutCenter'
  title: string
  content: string
  images: Array<{
    image: ImageWithAlt
    _key: string
  }>
}

export type Hero = {
  _type: 'hero'
  marker?: boolean
}

export type CourseDay = {
  _type: 'courseDay'
  title: string
  desc: string
}

export type FaqItem = {
  _type: 'faqItem'
  title: string
  answer: string
}

export type IconWithTitle = {
  _type: 'iconWithTitle'
  ikona: ImageWithAlt
  title: string
}

export type InstagramImage = {
  _type: 'instagramImage'
  image: ImageWithAlt
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  altText: string
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
}

export type Course = {
  _id: string
  _type: 'course'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  featuredImage: ImageWithAlt
  courseInformations: {
    people: {
      min: number
      max: number
    }
    place: string
    price: number
  }
  pageBuilder: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & AboutCenter)
    | ({
        _key: string
      } & Courses)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & SubHero)
    | ({
        _key: string
      } & AboutUsContent)
    | ({
        _key: string
      } & ThreeParagraphs)
    | ({
        _key: string
      } & ImageBlock)
    | ({
        _key: string
      } & CoursePlan)
    | ({
        _key: string
      } & IconsAndTitles)
    | ({
        _key: string
      } & TextContent)
    | ({
        _key: string
      } & TitleAndRichText)
    | ({
        _key: string
      } & CourseForm)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & Price)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & Instagram)
  >
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Global = {
  _id: string
  _type: 'global'
  _createdAt: string
  _updatedAt: string
  _rev: string
  options: {
    email: string
    facebook?: string
    instagram?: string
    telefon: string
    instagramimages: Array<
      {
        _key: string
      } & InstagramImage
    >
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  seo?: Seo
  pageBuilder: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & AboutCenter)
    | ({
        _key: string
      } & Courses)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & SubHero)
    | ({
        _key: string
      } & AboutUsContent)
    | ({
        _key: string
      } & ThreeParagraphs)
    | ({
        _key: string
      } & ImageBlock)
    | ({
        _key: string
      } & CoursePlan)
    | ({
        _key: string
      } & IconsAndTitles)
    | ({
        _key: string
      } & TextContent)
    | ({
        _key: string
      } & TitleAndRichText)
    | ({
        _key: string
      } & CourseForm)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & Price)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & Instagram)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Instagram
  | Gallery
  | Price
  | ContactForm
  | CourseForm
  | TitleAndRichText
  | TextContent
  | IconsAndTitles
  | CoursePlan
  | ImageBlock
  | ThreeParagraphs
  | AboutUsContent
  | SubHero
  | Faq
  | CourseReference
  | Courses
  | AboutCenter
  | Hero
  | CourseDay
  | FaqItem
  | IconWithTitle
  | InstagramImage
  | SanityImageAssetReference
  | ImageWithAlt
  | Seo
  | Course
  | Slug
  | Global
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
